/* eslint-disable @stylistic/max-len */
export { authenticateWithGoogle } from './auth/authenticate-with-google'
export { authenticateWithPassword } from './auth/authenticate-with-password'
export { createUser } from './auth/create-user'
export { getProfile } from './auth/get-profile'
export { getUsers } from './auth/get-users'
export { requestPasswordRecover } from './auth/request-password-recover'
export { resetPassword } from './auth/reset-password'

export { createOption } from './product/create-option'
export { createOptionValue } from './product/create-option-value'
export { createProduct } from './product/create-product'
export { deleteProduct } from './product/delete-product'
export { getAllOptions } from './product/get-options'
export { getProductById } from './product/get-product-by-id'
export { getProductBySlug } from './product/get-product-by-slug'
export { getAllProducts } from './product/get-products'
export { updateProduct } from './product/update-product'

export { createOrder } from './orders/create-order'
export { deleteOrder } from './orders/delete-order'
export { getOrdersByCustomer } from './orders/get-order-by-customer'
export { getOrderById } from './orders/get-order-by-id'
export { getOrders } from './orders/get-orders'
export { getOrdersStats } from './orders/get-orders-stats'
export { updateOrder } from './orders/update-order'
export { updateOrderStatus } from './orders/update-status-order'
export { updateStatusOrderToCancel } from './orders/update-status-order-to-cancel'

export { createAddress } from './address/create-address'
export { deleteAddress } from './address/delete-address'
export { getAddressById } from './address/get-address-by-id'
export { getAddresses } from './address/get-addresses'
export { setDefaultAddress } from './address/set-default-address'
export { updateAddress } from './address/update-address'

export { addToCart } from './cart/add-to-cart'
export { checkout } from './cart/checkout'
export { clearCart } from './cart/clear-cart'
export { getCart } from './cart/get-cart'
export { removeFromCart } from './cart/remove-item-from-cart'
export { updateCartItem } from './cart/update-cart-item'

export { adjustStock } from './stock/adjust-stock'
export { bulkUpdateStock } from './stock/bulk-update-stock'
export { getLowStockProducts } from './stock/get-low-stock-products'
export { getProductStock } from './stock/get-stock-product'
export { getStockReport } from './stock/get-stock-report'
export { getVariantStock } from './stock/get-variant-stock'
export { updateVariantStock } from './stock/variant-update-stock'

export { createCategory } from './categories/create-category'
export { deleteCategory } from './categories/delete-category'
export { getCategories } from './categories/get-categories'
export { getCategoryById } from './categories/get-category-by-id'
export { updateCategory } from './categories/update-category'

export { createBrand } from './brand/create-brand'
export { deleteBrand } from './brand/delete-brand'
export { getBrandById } from './brand/get-brand-by-id'
export { getBrands } from './brand/get-brands'
export { updateBrand } from './brand/update-brand'

